---
Name: myroutes
After:
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'api/auth': 'Bookings\Controllers\AuthenticationController'
    'api/company': 'Bookings\Controllers\CompanyController'